import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"

export function Faq() {
  return (
    <section className="py-12 border-t" aria-labelledby="faq-heading">
      <div className="container mx-auto px-4">
        <h2 id="faq-heading" className="text-2xl font-bold mb-6">
          Frequently Asked Questions
        </h2>

        <Accordion type="single" collapsible className="w-full">
          <AccordionItem value="item-1">
            <AccordionTrigger>What is a QR code?</AccordionTrigger>
            <AccordionContent>
              A QR code (Quick Response code) is a two-dimensional barcode that can be scanned using smartphones and
              dedicated QR code readers. QR codes can store various types of information such as URLs, text, contact
              information, and more. When scanned, they quickly direct users to websites, display text, or perform other
              actions based on the encoded data.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-2">
            <AccordionTrigger>How do I create a QR code?</AccordionTrigger>
            <AccordionContent>
              Creating a QR code with our generator is simple:
              <ol className="list-decimal pl-6 mt-2 space-y-1">
                <li>Select the type of content (URL, text, email, phone, etc.)</li>
                <li>Enter your content in the input field</li>
                <li>Customize the appearance (colors, size, error correction)</li>
                <li>Preview your QR code in real-time</li>
                <li>Download your QR code in your preferred format (PNG, JPEG, or SVG)</li>
              </ol>
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-3">
            <AccordionTrigger>Are the QR codes generated by this tool free to use?</AccordionTrigger>
            <AccordionContent>
              Yes, all QR codes generated by our tool are completely free to use for both personal and commercial
              purposes. There are no hidden fees, watermarks, or limitations on the number of QR codes you can create.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-4">
            <AccordionTrigger>What is error correction in QR codes?</AccordionTrigger>
            <AccordionContent>
              Error correction is a feature that allows QR codes to remain scannable even if they are partially damaged
              or obscured. Our generator offers four levels of error correction:
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>
                  <strong>Low (L):</strong> 7% of codewords can be restored
                </li>
                <li>
                  <strong>Medium (M):</strong> 15% of codewords can be restored
                </li>
                <li>
                  <strong>Quartile (Q):</strong> 25% of codewords can be restored
                </li>
                <li>
                  <strong>High (H):</strong> 30% of codewords can be restored
                </li>
              </ul>
              Higher error correction levels make the QR code more resilient but also more complex (denser).
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-5">
            <AccordionTrigger>Which format should I download my QR code in?</AccordionTrigger>
            <AccordionContent>
              We offer three download formats:
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>
                  <strong>PNG:</strong> Best for digital use and most versatile
                </li>
                <li>
                  <strong>JPEG:</strong> Good for web use where file size matters
                </li>
                <li>
                  <strong>SVG:</strong> Vector format that can be scaled to any size without losing quality, ideal for
                  printing
                </li>
              </ul>
              For most purposes, PNG is recommended. If you plan to print your QR code in large formats, SVG is the best
              choice.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-6">
            <AccordionTrigger>How do I scan a QR code?</AccordionTrigger>
            <AccordionContent>
              Most modern smartphones can scan QR codes using their built-in camera apps:
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>
                  <strong>iPhone:</strong> Open the Camera app and point it at the QR code
                </li>
                <li>
                  <strong>Android:</strong> Open the Camera app or Google Lens and point it at the QR code
                </li>
              </ul>
              If your camera doesn't automatically scan QR codes, you may need to download a dedicated QR code scanner
              app from your app store.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-7">
            <AccordionTrigger>Can I track how many times my QR code is scanned?</AccordionTrigger>
            <AccordionContent>
              Our basic QR code generator doesn't include tracking functionality. However, you can create trackable QR
              codes by:
              <ol className="list-decimal pl-6 mt-2 space-y-1">
                <li>Using a URL shortener service that offers analytics (like Bitly or TinyURL)</li>
                <li>Creating a QR code that points to your shortened URL</li>
                <li>Using the analytics provided by the URL shortener service</li>
              </ol>
              This method will allow you to track how many times your QR code is scanned.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </section>
  )
}
